### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by kimdele** [dmauser/opnazure#57]
Hi

When trying deploy this on Azure, the deployment failed on the CustomScript part on the created VM.
not sure, but it looks like it may be related to the WAAgent

anybody have a solutions for this ?

{"code":"DeploymentFailed","target":"/subscriptions/91d2505c-3c35-4ed8-9a08-759ff6????????/resourceGroups/opensense2/providers/Microsoft.Resources/deployments/OPNsense-TwoNics","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"ResourceDeploymentFailure","target":"/subscriptions/91d2505c-3c35-4ed8-9a08-759ff6????????/resourceGroups/opensense2/providers/Microsoft.Compute/virtualMachines/OPNsense/extensions/CustomScript","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'CustomScript' (publisher 'Microsoft.OSTCExtensions' and type 'CustomScriptForLinux'). Error message: 'Command returned an error.\n---stdout---\nn3.8/site-packages/azurelinuxagent/ga/env.py to env.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/exthandlers.py to exthandlers.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/monitor.py to monitor.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/periodic_operation.py to periodic_operation.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/remoteaccess.py to remoteaccess.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/send_telemetry_events.py to send_telemetry_events.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/ga/update.py to update.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/__init__.py to __init__.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/__init__.py to __init__.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/arch.py to arch.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/clearlinux.py to clearlinux.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/coreos.py to coreos.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/default.py to default.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/factory.py to factory.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/deprovision/ubuntu.py to ubuntu.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/provision/__init__.py to __init__.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/provision/cloudinit.py to cloudinit.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/provision/cloudinitdetect.py to cloudinitdetect.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/provision/default.py to default.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/provision/factory.py to factory.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/rdma/__init__.py to __init__.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/rdma/centos.py to centos.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/rdma/factory.py to factory.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/rdma/suse.py to suse.cpython-38.pyc\nbyte-compiling /usr/local/lib/python3.8/site-packages/azurelinuxagent/pa/rdma/ubuntu.py to ubuntu.cpython-38.pyc\nrunning install_data\ncopying bin/waagent -> /usr/local/sbin\ncopying bin/waagent2.0 -> /usr/local/sbin\ncopying config/freebsd/waagent.conf -> /etc\ncopying init/freebsd/waagent -> /etc/rc.d/\nrunning install_egg_info\nrunning egg_info\ncreating WALinuxAgent.egg-info\nwriting WALinuxAgent.egg-info/PKG-INFO\nwriting dependency_links to WALinuxAgent.egg-info/dependency_links.txt\nwriting requirements to WALinuxAgent.egg-info/requires.txt\nwriting top-level names to WALinuxAgent.egg-info/top_level.txt\nwriting manifest file 'WALinuxAgent.egg-info/SOURCES.txt'\nreading manifest file 'WALinuxAgent.egg-info/SOURCES.txt'\nreading manifest template 'MANIFEST.in'\nadding license file 'LICENSE.txt'\nadding license file 'NOTICE'\nwriting manifest file 'WALinuxAgent.egg-info/SOURCES.txt'\nCopying WALinuxAgent.egg-info to /usr/local/lib/python3.8/site-packages/WALinuxAgent-2.9.0.4-py3.8.egg-info\nrunning install_scripts\nUpdating FreeBSD repository catalogue...\nFreeBSD repository is up to date.\nAll repositories are up to date.\nChecking integrity... done (0 conflicting)\nThe most recent versions of packages are already installed\n\nBinding static ARP pair(s): azvip.\n\n\n---errout---\n2.9.0.4/tests/data/wire/version_info.xml\nx WALinuxAgent-2.9.0.4/tests/distro/\nx WALinuxAgent-2.9.0.4/tests/distro/__init__.py\nx WALinuxAgent-2.9.0.4/tests/distro/test_resourceDisk.py\nx WALinuxAgent-2.9.0.4/tests/distro/test_scvmm.py\nx WALinuxAgent-2.9.0.4/tests/ga/\nx WALinuxAgent-2.9.0.4/tests/ga/__init__.py\nx WALinuxAgent-2.9.0.4/tests/ga/extension_emulator.py\nx WALinuxAgent-2.9.0.4/tests/ga/mocks.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_collect_logs.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_collect_telemetry_events.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_env.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_extension.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_exthandlers.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_exthandlers_download_extension.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_exthandlers_exthandlerinstance.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_monitor.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_multi_config_extension.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_periodic_operation.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_remoteaccess.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_remoteaccess_handler.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_report_status.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_send_telemetry_events.py\nx WALinuxAgent-2.9.0.4/tests/ga/test_update.py\nx WALinuxAgent-2.9.0.4/tests/pa/\nx WALinuxAgent-2.9.0.4/tests/pa/__init__.py\nx WALinuxAgent-2.9.0.4/tests/pa/test_deprovision.py\nx WALinuxAgent-2.9.0.4/tests/pa/test_provision.py\nx WALinuxAgent-2.9.0.4/tests/protocol/\nx WALinuxAgent-2.9.0.4/tests/protocol/HttpRequestPredicates.py\nx WALinuxAgent-2.9.0.4/tests/protocol/__init__.py\nx WALinuxAgent-2.9.0.4/tests/protocol/mocks.py\nx WALinuxAgent-2.9.0.4/tests/protocol/mockwiredata.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_datacontract.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_extensions_goal_state_from_extensions_config.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_extensions_goal_state_from_vm_settings.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_goal_state.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_healthservice.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_hostplugin.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_image_info_matcher.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_imds.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_metadata_server_migration_util.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_protocol_util.py\nx WALinuxAgent-2.9.0.4/tests/protocol/test_wire.py\nx WALinuxAgent-2.9.0.4/tests/test_agent.py\nx WALinuxAgent-2.9.0.4/tests/tools.py\nx WALinuxAgent-2.9.0.4/tests/utils/\nx WALinuxAgent-2.9.0.4/tests/utils/__init__.py\nx WALinuxAgent-2.9.0.4/tests/utils/cgroups_tools.py\nx WALinuxAgent-2.9.0.4/tests/utils/event_logger_tools.py\nx WALinuxAgent-2.9.0.4/tests/utils/miscellaneous_tools.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_archive.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_crypt_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_extension_process_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_file_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_flexible_version.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_network_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_passwords.txt\nx WALinuxAgent-2.9.0.4/tests/utils/test_rest_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_shell_util.py\nx WALinuxAgent-2.9.0.4/tests/utils/test_text_util.py\nln: /usr/local/bin/python: File exists\nactions_waagent.conf                                   357  B 6330 kBps    00s\ncp: /usr/local/opnsense/service/conf/actions.d: No such file or directory\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory\nchmod: /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/20-freebsd: No such file or directory\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory\nconfigureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory\nchmod: /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory\n\n'. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot. "}]}]}

**Comment by dmauser** [comment]
Thanks for the heads up. We are investigating.

**Comment by jeffdmipshell** [comment]
I also am running into this issue.  Thanks Daniel for this deployment.  I use this to help customers with routing/azure network POCs.

**Comment by Welasco** [comment]
Problem solved in the latest PR https://github.com/dmauser/opnazure/pull/59

**Comment by dmauser** [comment]
@kimdele  and @jeffdmipshell. Deployment has been fixed. Can you redeploy it and check if it is working for you too?
Thanks!

**Comment by dmauser** [comment]
Deployments fixed, closing this issue

**Comment by HartD92** [comment]
@dmauser @Welasco I am still having this issue. This is what I'm getting on the latest version of the script.

VM has reported a failure when processing extension 'CustomScript' (publisher 'Microsoft.OSTCExtensions' and type 'CustomScriptForLinux'). Error message: 'Command returned an error.
---stdout---
9.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/ga/remoteaccess.py to remoteaccess.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/ga/send_telemetry_events.py to send_telemetry_events.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/ga/update.py to update.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/__init__.py to __init__.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/__init__.py to __init__.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/arch.py to arch.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/clearlinux.py to clearlinux.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/coreos.py to coreos.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/default.py to default.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/factory.py to factory.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/deprovision/ubuntu.py to ubuntu.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/provision/__init__.py to __init__.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/provision/cloudinit.py to cloudinit.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/provision/cloudinitdetect.py to cloudinitdetect.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/provision/default.py to default.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/provision/factory.py to factory.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/rdma/__init__.py to __init__.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/rdma/centos.py to centos.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/rdma/factory.py to factory.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/rdma/suse.py to suse.cpython-39.pyc
byte-compiling /usr/local/lib/python3.9/site-packages/azurelinuxagent/pa/rdma/ubuntu.py to ubuntu.cpython-39.pyc
running install_data
copying bin/waagent -> /usr/local/sbin
copying bin/waagent2.0 -> /usr/local/sbin
copying config/freebsd/waagent.conf -> /etc
copying init/freebsd/waagent -> /etc/rc.d/
running install_egg_info
running egg_info
creating WALinuxAgent.egg-info
writing WALinuxAgent.egg-info/PKG-INFO
writing dependency_links to WALinuxAgent.egg-info/dependency_links.txt
writing requirements to WALinuxAgent.egg-info/requires.txt
writing top-level names to WALinuxAgent.egg-info/top_level.txt
writing manifest file 'WALinuxAgent.egg-info/SOURCES.txt'
reading manifest file 'WALinuxAgent.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.txt'
adding license file 'NOTICE'
writing manifest file 'WALinuxAgent.egg-info/SOURCES.txt'
Copying WALinuxAgent.egg-info to /usr/local/lib/python3.9/site-packages/WALinuxAgent-2.9.1.1-py3.9.egg-info
running install_scripts
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Updating database digests format: . done
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be UPGRADED:
	bash: 5.2.15 -> 5.2.26_1

Number of packages to be upgraded: 1

2 MiB to be downloaded.
[1/1] Fetching bash-5.2.26_1.pkg: .......... done
Checking integrity... done (0 conflicting)
[1/1] Upgrading bash from 5.2.15 to 5.2.26_1...
[1/1] Extracting bash-5.2.26_1: .......... done
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.

Binding static ARP pair(s): azvip.


---errout---
lib/agent_test_suite.py
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/lib/agent_test_suite_combinator.py
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/runbook.yml
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/sample_runbooks/
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/sample_runbooks/existing_vm.yml
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/sample_runbooks/local_machine/
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/sample_runbooks/local_machine/hello_world.py
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/sample_runbooks/local_machine/local.yml
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/check-agent-log.py
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/collect-logs
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/get-agent-bin-path
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/get-agent-modules-path
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/get-agent-python
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/install-agent
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/install-tools
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/uncompress.py
x WALinuxAgent-2.9.1.1/tests_e2e/orchestrator/scripts/unzip.py
x WALinuxAgent-2.9.1.1/tests_e2e/pipeline/
x WALinuxAgent-2.9.1.1/tests_e2e/pipeline/pipeline-cleanup.yml
x WALinuxAgent-2.9.1.1/tests_e2e/pipeline/pipeline.yml
x WALinuxAgent-2.9.1.1/tests_e2e/pipeline/scripts/
x WALinuxAgent-2.9.1.1/tests_e2e/pipeline/scripts/execute_tests.sh
x WALinuxAgent-2.9.1.1/tests_e2e/test_suites/
x WALinuxAgent-2.9.1.1/tests_e2e/test_suites/agent_bvt.yml
x WALinuxAgent-2.9.1.1/tests_e2e/test_suites/fail.yml
x WALinuxAgent-2.9.1.1/tests_e2e/test_suites/images.yml
x WALinuxAgent-2.9.1.1/tests_e2e/test_suites/pass.yml
x WALinuxAgent-2.9.1.1/tests_e2e/tests/
x WALinuxAgent-2.9.1.1/tests_e2e/tests/__init__.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/bvts/
x WALinuxAgent-2.9.1.1/tests_e2e/tests/bvts/__init__.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/bvts/extension_operations.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/bvts/run_command.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/bvts/vm_access.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/error_test.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/fail_test.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/__init__.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/agent_log.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/agent_test.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/agent_test_context.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/identifiers.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/logging.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/retry.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/shell.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/ssh_client.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/virtual_machine.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/lib/vm_extension.py
x WALinuxAgent-2.9.1.1/tests_e2e/tests/pass_test.py
/usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
ln: /usr/local/bin/python: File exists
actions_waagent.conf                                   357  B 4778 kBps    00s
cp: /usr/local/opnsense/service/conf/actions.d: No such file or directory
pkg: No packages available to install matching 'os-frr' have been found in the repositories
configureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory
chmod: /usr/local/etc/rc.syshook.d/start/22-remoteroute: No such file or directory
configureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/20-freebsd: No such file or directory
configureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory
configureopnsense.sh: cannot create /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory
chmod: /usr/local/etc/rc.syshook.d/start/94-restartwebgui: No such file or directory

'. More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot.  (Code: VMExtensionProvisioningError)
